### ISSUE TITLE
Fix tests failing on py3.7

### ISSUE THREAD

**Issue by RJ722** [jendrikseipp/vulture#117]
There's currently one test failing on python3.7:
```py
if sys.version_info > (3, 0):
    check_conditions("1-1", False)
```

Interestingly the same error is raised by `ast.literal_eval` in python2.7 which we bypass in the test.

Error in 3.7:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 91, in literal_eval
    return _convert(node_or_string)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 90, in _convert
    return _convert_signed_num(node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 63, in _convert_signed_num
    return _convert_num(node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 55, in _convert_num
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.BinOp object at 0x10d2bfa58>
```
Error in 2.7:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/ast.py", line 68, in literal_eval
    return _convert(node_or_string)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/ast.py", line 67, in _convert
    raise ValueError('malformed string')
ValueError: malformed string
```

I think we should remove this test, I guess `1-1` isn't of utmost important after all :-p

**Comment by jendrikseipp** [comment]
I found this issue which explains the change in behaviour: https://bugs.python.org/issue31778.

I think we should change the code to (add appropriate line break)

```
# Only Python 3.0-3.6 allows addition and subtraction in ast.literal_eval (see https://bugs.python.org/issue31778).
if (3, 0) <= sys.version_info < (3, 7):
    check_conditions("1-1", False)
```

**Comment by RJ722** [comment]
Yes, let's do that.
