### ISSUE TITLE
Python 3.12: DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead

### ISSUE THREAD

**Issue by The-Compiler** [jendrikseipp/vulture#314]
With an `x.py` such as:

```python
hasattr("", "test")
```

running Python 3.12.0b2 via `python3.12 -Werror -m vulture x.py` results in:

```pytb
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/florian/tmp/vultdeprecation/.venv/lib/python3.12/site-packages/vulture/__main__.py", line 3, in <module>
    main()
  File "/home/florian/tmp/vultdeprecation/.venv/lib/python3.12/site-packages/vulture/core.py", line 725, in main
    vulture.scavenge(config["paths"], exclude=config["exclude"])
  File "/home/florian/tmp/vultdeprecation/.venv/lib/python3.12/site-packages/vulture/core.py", line 289, in scavenge
    self.scan(module_string, filename=module)
  File "/home/florian/tmp/vultdeprecation/.venv/lib/python3.12/site-packages/vulture/core.py", line 256, in scan
    self.visit(node)
  File "/home/florian/tmp/vultdeprecation/.venv/lib/python3.12/site-packages/vulture/core.py", line 681, in visit
    return self.generic_visit(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/vultdeprecation/.venv/lib/python3.12/site-packages/vulture/core.py", line 713, in generic_visit
    self.visit(item)
  File "/home/florian/tmp/vultdeprecation/.venv/lib/python3.12/site-packages/vulture/core.py", line 681, in visit
    return self.generic_visit(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/vultdeprecation/.venv/lib/python3.12/site-packages/vulture/core.py", line 715, in generic_visit
    self.visit(value)
  File "/home/florian/tmp/vultdeprecation/.venv/lib/python3.12/site-packages/vulture/core.py", line 666, in visit
    visitor(node)
  File "/home/florian/tmp/vultdeprecation/.venv/lib/python3.12/site-packages/vulture/core.py", line 528, in visit_Call
    if isinstance(attr_name_arg, ast.Str):
                                 ^^^^^^^
  File "/usr/lib/python3.12/ast.py", line 1787, in __getattr__
    warnings._deprecated(
  File "/usr/lib/python3.12/warnings.py", line 529, in _deprecated
    warn(msg, DeprecationWarning, stacklevel=3)
DeprecationWarning: ast.Str is deprecated and will be removed in Python 3.14; use ast.Constant instead
```

**Comment by jendrikseipp** [comment]
Good point!
