### ISSUE TITLE
Tests fail with python 3.11

### ISSUE THREAD

**Issue by inglor** [jendrikseipp/vulture#325]
Tests fails when trying to package Archlinux package:

```
cleanup: install_deps> python -I -m pip install coverage==7.0.5
.pkg: install_requires> python -I -m pip install 'setuptools>=40.8.0' wheel
.pkg: _optional_hooks> python /usr/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_wheel> python /usr/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: install_requires_for_build_wheel> python -I -m pip install wheel
cleanup: internal error
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/tox/session/cmd/run/single.py", line 45, in _evaluate
    tox_env.setup()
  File "/usr/lib/python3.11/site-packages/tox/tox_env/api.py", line 250, in setup
    self._setup_with_env()
  File "/usr/lib/python3.11/site-packages/tox/tox_env/runner.py", line 143, in _setup_with_env
    self._setup_pkg()
  File "/usr/lib/python3.11/site-packages/tox/tox_env/runner.py", line 166, in _setup_pkg
    self._packages = self._build_packages()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/runner.py", line 118, in _build_packages
    packages = package_env.perform_packaging(self.conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/package.py", line 47, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 186, in perform_packaging
    deps = self._load_deps(for_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/package.py", line 47, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 239, in _load_deps
    deps = self._load_deps_from_built_metadata(for_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/package.py", line 47, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 283, in _load_deps_from_built_metadata
    reqs = self.get_package_dependencies(for_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/package.py", line 47, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 292, in get_package_dependencies
    self._ensure_meta_present(for_env)
  File "/usr/lib/python3.11/site-packages/tox/tox_env/package.py", line 47, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 312, in _ensure_meta_present
    dist_info = end.prepare_metadata_for_build_wheel(self.meta_folder, self._wheel_config_settings).metadata
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'metadata'
cleanup: FAIL ✖ in 1.96 seconds
py37: skipped because could not find python interpreter with spec(s): py37
py37: SKIP ⚠ in 0.03 seconds
py38: skipped because could not find python interpreter with spec(s): py38
py38: SKIP ⚠ in 0 seconds
py310: skipped because could not find python interpreter with spec(s): py310
py310: SKIP ⚠ in 0 seconds
py311: install_deps> python -I -m pip install coverage==7.0.5 pint pytest-cov==4.0.0 pytest==7.2.1
py311: internal error
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/tox/session/cmd/run/single.py", line 45, in _evaluate
    tox_env.setup()
  File "/usr/lib/python3.11/site-packages/tox/tox_env/api.py", line 250, in setup
    self._setup_with_env()
  File "/usr/lib/python3.11/site-packages/tox/tox_env/runner.py", line 143, in _setup_with_env
    self._setup_pkg()
  File "/usr/lib/python3.11/site-packages/tox/tox_env/runner.py", line 166, in _setup_pkg
    self._packages = self._build_packages()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/runner.py", line 118, in _build_packages
    packages = package_env.perform_packaging(self.conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/package.py", line 47, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 186, in perform_packaging
    deps = self._load_deps(for_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/package.py", line 47, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 239, in _load_deps
    deps = self._load_deps_from_built_metadata(for_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/package.py", line 47, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 283, in _load_deps_from_built_metadata
    reqs = self.get_package_dependencies(for_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/package.py", line 47, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 292, in get_package_dependencies
    self._ensure_meta_present(for_env)
  File "/usr/lib/python3.11/site-packages/tox/tox_env/package.py", line 47, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 312, in _ensure_meta_present
    dist_info = end.prepare_metadata_for_build_wheel(self.meta_folder, self._wheel_config_settings).metadata
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'metadata'
py311: FAIL ✖ in 1.86 seconds
style: install_deps> python -I -m pip install black==22.3.0 flake8-2020==1.7.0 flake8-bugbear==23.1.14 flake8-comprehensions==3.10.1 flake8==6.0.0 pyupgrade==2.28.0
style: internal error
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/tox/session/cmd/run/single.py", line 45, in _evaluate
    tox_env.setup()
  File "/usr/lib/python3.11/site-packages/tox/tox_env/api.py", line 250, in setup
    self._setup_with_env()
  File "/usr/lib/python3.11/site-packages/tox/tox_env/runner.py", line 143, in _setup_with_env
    self._setup_pkg()
  File "/usr/lib/python3.11/site-packages/tox/tox_env/runner.py", line 166, in _setup_pkg
    self._packages = self._build_packages()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/runner.py", line 118, in _build_packages
    packages = package_env.perform_packaging(self.conf)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/package.py", line 47, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 186, in perform_packaging
    deps = self._load_deps(for_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/package.py", line 47, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 239, in _load_deps
    deps = self._load_deps_from_built_metadata(for_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/package.py", line 47, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 283, in _load_deps_from_built_metadata
    reqs = self.get_package_dependencies(for_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/package.py", line 47, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 292, in get_package_dependencies
    self._ensure_meta_present(for_env)
  File "/usr/lib/python3.11/site-packages/tox/tox_env/package.py", line 47, in _func
    return meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tox/tox_env/python/virtual_env/package/pyproject.py", line 312, in _ensure_meta_present
    dist_info = end.prepare_metadata_for_build_wheel(self.meta_folder, self._wheel_config_settings).metadata
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'metadata'
.pkg: _exit> python /usr/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
  cleanup: FAIL code 2 (1.96 seconds)
  py37: SKIP (0.03 seconds)
  py38: SKIP (0.00 seconds)
  py310: SKIP (0.00 seconds)
  py311: FAIL code 2 (1.86 seconds)
  style: FAIL code 2 (1.99 seconds)
  evaluation failed :( (5.86 seconds)
[1m[31m==> ERROR:(B[m[1m A failure occurred in check().(B[m
[1m    Aborting...(B[m

```

**Comment by The-Compiler** [comment]
This is indeed a tox (or its deps) issue on Archlinux. I see the same when running pytest tests, see https://github.com/tox-dev/tox/issues/3110.

**Comment by The-Compiler** [comment]
I opened an Archlinux bug now: [FS#79602 : [python-tox] Incompatible with python-pyproject-api 1.6.1](https://bugs.archlinux.org/task/79602)

**Comment by inglor** [comment]
Thanks for the pointer. Both packages in -testing for now ([python-tox], [vulture]), let's see what breaks :)

[python-tox]: https://archlinux.org/packages/extra-testing/any/python-tox/
[vulture]: https://archlinux.org/packages/extra-testing/any/vulture/
