### ISSUE TITLE
--sort-by-size causes issues with exec

### ISSUE THREAD

**Issue by mjalkio** [jendrikseipp/vulture#72]
Hi, I'm experiencing issues with the `--sort-by-size` flag and the `exec` statement. If we have a very simple file `test.py`:

```
def foo():
    exec('print("bar")')

foo()
```

I can run `vulture test.py` without issues. However, if I run `vulture test.py --sort-by-size` I get the following output:
```
Traceback (most recent call last):
  File "/Users/mjalkio/Code/classypy/venv/bin/vulture", line 11, in <module>
    sys.exit(main())
  File "/Users/mjalkio/Code/classypy/venv/lib/python2.7/site-packages/vulture/core.py", line 414, in main
    vulture.scavenge(args)
  File "/Users/mjalkio/Code/classypy/venv/lib/python2.7/site-packages/vulture/core.py", line 153, in scavenge
    self.scan(module_string, filename=module)
  File "/Users/mjalkio/Code/classypy/venv/lib/python2.7/site-packages/vulture/core.py", line 114, in scan
    self.visit(node)
  File "/Users/mjalkio/Code/classypy/venv/lib/python2.7/site-packages/vulture/core.py", line 384, in visit
    return self.generic_visit(node)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ast.py", line 249, in generic_visit
    self.visit(item)
  File "/Users/mjalkio/Code/classypy/venv/lib/python2.7/site-packages/vulture/core.py", line 381, in visit
    visitor(node)
  File "/Users/mjalkio/Code/classypy/venv/lib/python2.7/site-packages/vulture/core.py", line 292, in visit_FunctionDef
    self.defined_funcs.append(self._get_item(node, 'function'))
  File "/Users/mjalkio/Code/classypy/venv/lib/python2.7/site-packages/vulture/core.py", line 256, in _get_item
    size = lines.count_lines(node) if self.sort_by_size else 1
  File "/Users/mjalkio/Code/classypy/venv/lib/python2.7/site-packages/vulture/lines.py", line 29, in count_lines
    return get_last_line_number(node) - node.lineno + 1
  File "/Users/mjalkio/Code/classypy/venv/lib/python2.7/site-packages/vulture/lines.py", line 18, in get_last_line_number
    last_child = _get_last_child(node)
  File "/Users/mjalkio/Code/classypy/venv/lib/python2.7/site-packages/vulture/lines.py", line 12, in _get_last_child
    return last_children[-1]
TypeError: 'Str' object does not support indexing
```

Do you have any idea why this is?

**Comment by jendrikseipp** [comment]
Thanks for the report! This issue should be fixed now in the repo. Can you confirm this?
